export const RED_CHANNELS = 'RED_CHANNELS';
export const RED_CHANNEL_MESSAGES = 'RED_CHANNEL_MESSAGES';
export const RED_CHANNEL_USERS = 'RED_CHANNEL_USERS';
export const RED_FORGOT_PASSWORD_TOKEN = 'RED_FORGOT_PASSWORD_TOKEN:';
export const RED_VERIFY_EMAIL_TOKEN = 'RED_VERIFY_EMAIL_TOKEN:';
