export const NEW_MESSAGE = 'NEW_MESSAGE';
export const REMOVED_MESSAGE = 'REMOVED_MESSAGE';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const GLOBAL_NOTIFICATION = 'GLOBAL_NOTIFICATION';
