# secret will be stored inside the kubernetes and no one outside can access it
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  # Opaque => key value
  # other secret types can be TLS certificate etc
type: Opaque
data:
  # base64 encoded =>
  # echo -n $value | base64
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
