apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: local # storage type => local (running kube on local)
spec:
  storageClassName: standard # kubectl get storageClass
  capacity:
    storage: 50Mi # 50mb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/redis-data' # redis storage path
