apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: local # storage type => local (running kube on local)
spec:
  storageClassName: standard # kubectl get storageClass
  capacity:
    storage: 50Mi # 50mb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/redis-data' # redis storage path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 10Mi
